model_id: xtuner/llava-phi-3-mini-hf
model_family: llava-phi

LoRA:
  r: 0
  alpha: 128
  dropout: 0.0

loss_type: grad_ascent       # fine for Stage 1, just runs CE
tune_vision_tower: True      
tune_mm_projector: True
tune_language_model: True

data_path: ./dataset/full.json
split: null                     # all 400 identities

batch_size: 4
gradient_accumulation_steps: 16
max_grad_norm: 1.0
num_epochs: 10               

save_dir: models/stage1_llava_phi_5epochs_lr2e5_full
save_steps: 290

lr: 2e-5                    
weight_decay: 0.00
seed: 0
workers: 4
lr_scheduler_type: "cosine"
warmup_ratio: 0.00           
max_train_steps: -1
report_to: "wandb"
resume_from_checkpoint: ""